# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Lh2k8fmJgLXn7iIpg6LxxFwmebOjUoi
"""

# Ejecuta esto en una celda de Colab
!pip install -q -U google-generativeai streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import google.generativeai as genai
# from PIL import Image
# 
# # 1. Configuración de la página
# st.set_page_config(page_title="ArqAI: Rediseño Estructural", layout="centered")
# st.title("🏗️ ArqAI: De Foto a Estructura")
# st.write("Sube una foto de una zona y recibe un rediseño técnico completo.")
# 
# # 2. Configurar la API (Aquí pondrás tu clave después)
# api_key = st.sidebar.text_input("Introduce tu Gemini API Key", type="password")
# 
# if api_key:
#     genai.configure(api_key=api_key)
#     model = genai.GenerativeModel('gemini-1.5-flash')
# 
#     # 3. Interfaz de usuario
#     archivo_subido = st.file_uploader("Elige una imagen...", type=["jpg", "jpeg", "png"])
#     comando = st.text_input("¿Qué quieres construir aquí?", "Diseña un estudio moderno de cristal y madera")
# 
#     if archivo_subido is not None and st.button("Generar Rediseño"):
#         imagen = Image.open(archivo_subido)
#         st.image(imagen, caption='Imagen Original', use_column_width=True)
# 
#         with st.spinner('Analizando estructura y materiales...'):
#             # El "Super Prompt" para que actúe como arquitecto
#             prompt = [
#                 f"Analiza esta imagen y actúa como arquitecto e ingeniero. "
#                 f"Rediseña la zona según este comando: {comando}. "
#                 f"Detalla: 1. Estructura propuesta. 2. Estabilidad de carga. 3. Materiales necesarios.",
#                 imagen
#             ]
#             response = model.generate_content(prompt)
# 
#             st.subheader("📋 Propuesta Técnica")
#             st.write(response.text)
# else:
#     st.warning("Por favor, introduce tu API Key en la barra lateral para comenzar.")
#